# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required
version: "3.5"

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  worker:
    image: cldcvr/codepipes-example-worker
    build:
      context: ./worker
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  vote:
    image: cldcvr/codepipes-example-vote
    build: ./vote
    depends_on:
      - redis
      - worker
    volumes:
      - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    image: cldcvr/codepipes-example-result
    build: ./result
    depends_on:
      - db
      - worker
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  

  redis:
    image: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    networks:
      - back-tier
